

PUT  http://localhost:3001/api/blogs/3
Content-Type: application/json

{
    "likes": 25 
}

### 
PUT  http://localhost:3001/api/blogs/3
Content-Type: application/json

{
    "likes": false
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test@email.com",
    "name": "Test"
}


###
PUT http://localhost:3001/api/users/user1
Content-Type: application/json

{
    "username": "userOne"
}

###
GET http://localhost:3001/api/users
Content-Type: application/json

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "test@email.com",
    "password": "secret"
}





