

PUT  http://localhost:3001/api/blogs/5
Content-Type: application/json

{
    "likes": 10 
}

### 
PUT  http://localhost:3001/api/blogs/3
Content-Type: application/json

{
    "likes": false
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test",
    "name": "Test"
}


###
PUT http://localhost:3001/api/users/user1
Content-Type: application/json

{
    "username": "userOne"
}

###
GET http://localhost:3001/api/users
Content-Type: application/json

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "user2@gmail.com",
    "password": "secret"
}

###
GET http://localhost:3001/api/blogs
Content-Type: application/json

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZW1haWwuY29tIiwiaWQiOjgsImlhdCI6MTc2MjM3MzI5MX0.hy735fVNRd6SHhR1QCTNH80tCW9Iy7hnTYxl8AaNcJI

{
    "author": "tester",
    "title": "test",
    "url": "testing.com"
}

###
DELETE http://localhost:3001/api/blogs/5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGdtYWlsLmNvbSIsImlkIjo1LCJpYXQiOjE3NjIzNzQ0OTB9.1-uG3rq7PHcOL3L0b6mojAM0jJsP5-DbA8hn0F8B5-s
